### ISSUE TITLE
LearnYouNode Exercises 12 -- no content in response object

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [rvagg/learnyounode#246]
I'm trying to avoid using the chunk-mapper module so I can play with nodejs as close as possible. 

```javascript
// Start program12 process

// Get the http module for Node
var http = require('http')

// Get the stream module for Node
var stream = require('stream')

http.createServer(function(req, res) {
   if(req["method"] != "POST")
      return res.end("Server responds to POST requests only.");

   // 'OK' HTTP code
   res.writeHead(200, {'content-type': 'text/plain'})

   res.on('data', function(data){
      data.toString().toUpperCase();
   });

   req.pipe(res);
   res.end();
}).listen(process.argv[2]);
```

With my understanding, when the request stream pipes into the response stream, it should trigger the data event and the result will have response object with uppercase words. As of right now, nothing is displaying.

**Comment by rvagg** [comment]
Using node is using packages from npm. Core is small, most of what you end up touching in a real node app comes from npm, hence its introduction in learnyounode. 

You will learn more about streams in streams adventure but I'd encourage you to embrace node-style modularity and do as suggested. 

The root of your problem is that your uppercased string isn't sent anywhere, you can write it to the response but you'll also need to watch for the 'end' event and end the response stream on that. Stuff that's taken care of for you when you use the abstractions.

**Comment by ralphtheninja** [comment]
@TheMaverickProgrammer It could look something like this:

```js
var body = ''
req.on('data', function (data) {
  body += data
})
.on('end', function () {
  res.end(body.toString().toUpperCase())
})
```

**Comment by TheMaverickProgrammer** [comment]
@ralphtheninja  That worked like a charm. Thanks for the snippet! It really sheds some light on how the components work together.

**Comment by diegofaria** [comment]
:+1:
