### ISSUE TITLE
What's wrong with my code of  BABY STEPS (Exercise 2 of 13)

### ISSUE THREAD

**Issue by PokimLee** [rvagg/learnyounode#277]
here's my cold in [program.js] : 

    var sum = 0;
    for (var i = 2;process.argv.length - 1; i++) {
  	  sum += Number(process.argv[i]);
    }
    console.log(sum);

________________

what's wrong with it?  when I run the [program.js], it was always calculating/runing but not giving me a result

**Comment by martinheidegger** [comment]
Your problem is in the for loop. The javascript syntax is  `for (<initial state>; <until condition>; <after every iteration>` Your `<until condition>` checks if the length is true ... which only will be the case if `process.argv.length` is 2 (`2-1 == true` in javascript). It should perhaps check for  `i<process.argv.length`.

**Comment by PokimLee** [comment]
It did help me a lot! Thanks very much!
